ApplicationManagement/urls.py
from django.conf.urls import url
from . import views as application_views

app_name = 'application'

# Application Registration Process
urlpatterns = [
    url(r'^$', application_views.user_registration, name='register_user'),
    url(r'^signup/(?P<role>.+)/$', application_views.AccountRegistrationView.as_view(), name='register_account'),
    url(r'^team/$', application_views.team_registration, name='register_team'),
    url(r'^student/$', application_views.StudentRegistrationView.as_view(), name='register_student'),
    url(r'^expert/$', application_views.ExpertRegistrationView.as_view(), name='register_expert'),
]

# Application Management Views
urlpatterns += [
    url(r'^review/$', application_views.review_overview, name='review_index'),
    url(r'^review/teams/(?P<slug>[-\w]+)/$', application_views.assess_teams, name='review_index'),
    url(r'^review/teams/', application_views.assess_teams, name='team_overview'),
    # url(r'^team/detail/(?P<role>\w+/$)', application_views.application_by, name='role_overview'),
    # url(r'^()', application_views.application_judgeOverview, name='')
]

Portal/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'portal'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^competition/$', views.CompetitionIndex.as_view(), name='competition'),
    url(r'^venue/$', views.VenueIndex.as_view(), name="venues"),
    url(r'^venue/manage/$', views.VenueManagementView.as_view(), name="manage_venue"),
    url(r'^venue/create/$', views.VenueCreate.as_view(), name='create_venue'),
    url(r'^venue/(?P<slug>.+)/', views.VenueDetailView.as_view(), name="venue_detail"),
    url(r'^teams/$', views.TeamListView.as_view(), name='teams'),
    url(r'^teams/(?P<slug>[\w\-]+)/$', views.TeamDetailView.as_view(), name="team_profile"),
    url(r'^teams/(?P<slug>[\w\-]+)/edit/$', views.TeamEditView.as_view(), name="edit_team"),
    url(r'^experts/$', views.ExpertListView.as_view(), name='experts'),
    url(r'^expert/(?P<slug>[\w\.]+)/$', views.ExpertDetailView.as_view(), name='expert_profile'),
    url(r'^students/$', views.StudentListView.as_view(), name="students"),
    url(r'^student/(?P<slug>[\w\.]+)/', views.StudentDetailView.as_view(), name='student_profile'),
    url(r'^session/', include('SessionManagement.urls')),
]

UserManagement/models.py
from datetime import datetime
from django.conf import settings
# General Imports

from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
# Automatic Account Association between User and Attendent Account in Registration
from django.db.models.signals import post_save
from django.dispatch import receiver
# Country Field import
from django_countries.fields import CountryField
# URL resolvers
from django.urls import reverse
# Calculation imports
from django.db.models import (Avg, StdDev, Sum, Max, Min)


PRACTICE_FIELDS = (
        ('negotiation', 'Negotiation'),
        ('mediation', 'Mediation'),
        ('arbitration', 'Arbitratiion')
    )
# -------------------  Roles within the Competition  ------------------

class Attendent(models.Model):
    """A Person attending the Competiton. Information stored to keep track
    on Applications before and behaviour during Competition over Time.
    Reused in later application processes."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=35, choices= settings.STUDENT_ROLES + settings.EXPERT_ROLES + settings.STAFF_ROLES)
    blacklisted = models.BooleanField(default=False)
    administrativeComment = models.TextField(blank=True, null=True)


    # Store Information on the Current Year for easy retrieval
    current_application = None

    def get_current_application(self):
        """
        Used to get the current application from inside a template.
        Returns None when no application present.
        """
        application = self.application_set.get(competition_year='2017')
        if application:
            return application
        else:
            return None

    def get_ratings(self, year=datetime.now().year):
        # Catch all given Feedback
        if self.feedback_set.all():
            # Calculate the AVG Values
            return self.feedback_set.filter(expert=self.user.attendent, date__year=year).aggregate(Avg('feedbackQuality'), Avg('feedbackRelated'), Avg('feedbackComm'))
        else:
            return None

    def get_absolute_url(self):
        return reverse('portal:expert_profile', args = [self.user.username])

    def __str__(self):
        return "{}".format(self.user.get_full_name())
    
    def save(self, *args, **kwargs):
        self.current_application = self.application_set.filter(competition_year=settings.START_DATE.year)
        super(Attendent, self).save(*args, **kwargs)


# This automatically creates an Attendent Instance for every User on save
# @receiver(post_save, sender=User)
# def create_attendent_profile(sender, instance, created, **kwargs):
#     if created:
#         Attendent.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_attendent_profile(sender, instance, **kwargs):
#     instance.attendent.save()



class Expert(Attendent):
    """
    
    """
    # Expert related Feedback Scores
    pass

class Team(Attendent):
    """Group of Students applying from a University for the Competition.
    Consisting of individual Team Members and an Associated Coach."""
    university = models.CharField(max_length=100)
    university_logo = models.ImageField(upload_to='team/university_logo/', blank=True)
    country = CountryField(null=True)
    teamImg = models.ImageField(upload_to='team/teampictures/', blank=True)
    slug = models.SlugField(blank=True, null=True)
    members = models.ManyToManyField(Attendent, related_name="teammembers")

    def __str__(self):
        return self.university
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.university)
        self.role = 'team'
        super().save(*args, **kwargs)


class Student(Attendent):
    """
    Can be in role(Mediator, Negotiator). profile 
    """
    # This needs to be initialized when the student is 
    university = models.OneToOneField(Team, null=True, blank=True)

class Staff(Attendent):
    """
    Will be used to manage and represent all necessary information on a Staff Member for Shift Management.
    """
    pass


# ---Basic Profile Models to store additional Information on the Applicants
class Profile(models.Model):
    """
    """
    attendent = models.OneToOneField(Attendent, blank=True, null=True, on_delete=models.CASCADE)
    bio = models.TextField(max_length=2000)
    slogan = models.CharField(max_length=250, verbose_name="Your favorite quote up to 250 characters")
    country = CountryField(null=True)
    city = models.CharField(max_length=50, verbose_name='City of Residence')
    profileImg = models.ImageField(upload_to='profileImg/%Y/%m/%d', blank=True, null=True)

    # Contact Details
    phoneNumber = models.CharField(verbose_name="Your Phone Number", max_length=100, blank=True, null=True)

    # Social Media Accounts
    twitter = models.URLField(verbose_name="Twitter Account",
    blank=True, null=True)
    linkedin = models.URLField(verbose_name="LinkedIn Account",
    blank=True, null=True)
    facebook = models.URLField(verbose_name="Facebook Account",
    blank=True, null=True)
    blog = models.URLField(verbose_name="Website",
    blank=True, null=True)

    def __str__(self):
        return str(self.attendent)

class ExpertProfile(Profile):
    """
    """
    coachedTeam = models.ForeignKey(Team, related_name="coachedTeam", null=True, blank=True)  
    affiliation = models.CharField(max_length=100)
    position = models.CharField(max_length=100)

    # Special Certifications and Memberships
    imi_certified = models.BooleanField(verbose_name="Are you IMI Certified?", default=False)
    viac_member = models.BooleanField(verbose_name="Are you Member of VIAC?", default=False)
    iba_member = models.BooleanField(verbose_name="Are you Member of IBA?", default=False)

class StudentProfile(Profile):
    """
    Stores all relevant information on the Student as either(Negotiator, Mediator) in the
    competition. Is used for professional representation, sharing of information.
    It does NOT store relevant Scoringinformation etc.(= stored on ATTENDENT )
    """
    # student = models.OneToOneField(Student, null=True, on_delete=models.CASCADE)
    
    # relevant practical Experience
    def get_absolute_url(self):
        return reverse('portal:student_profile', args=[self.attendent.user.username])

class TeamProfile(models.Model):
    """ Stores all relevant Information about the Team as the object of a Application.
    Relevant information about the Applicants as part of the team are stored in the
    'Student Profile' and assTociated to the Team Instance."""
    team = models.OneToOneField(Team, null=True, blank=True)
    languages_spoken = models.CharField(max_length=100, blank=True)

    # Application Relevant Information
    presentation_text = models.TextField(max_length=4000, blank=True)
    application_letter = models.FileField(verbose_name="Upload your motivation letter",
    upload_to='applications/teams/motivationletter/', 
    blank=True, null=True)

    application_video = models.FileField(verbose_name="Upload Application Video",
    blank=True, null=True) 

    # Additional Profile Information
    def __str__(self):
        return self.team.university
        
@receiver(post_save, sender=Team)
def create_tem_profile(sender, instance, created, **kwargs):
    if created:
        TeamProfile.objects.create(team=instance)

@receiver(post_save, sender=Team)
def save_team_profile(sender, instance, **kwargs):
    instance.teamprofile.save()


class StaffProfile(Profile):
    """
    Stores all relevant information on the Student as either(Negotiator, Mediator) in the
    competition. Is used for professional representation, sharing of information.
    It does NOT store relevant Scoringinformation etc.(= stored on ATTENDENT )
    """ 
    staff = models.OneToOneField(Staff, null=True, on_delete=models.CASCADE)
    
    # relevant practical Experience
    def get_absolute_url(self):
        return reverse('portal:student_profile', args=[self.attendent.user.username])


#----------------- Interaction models -------------------------

# ----- Feedback / Scoring Views --------
def score_list(request):
    score_list = ScoreSheet.objects.filter(pk=request.user.id)
    return render(request, 'profile/score_list.html', {
        'score_list': score_list,
    })

def score_detail(request, session_slug):
    session_scores = ScoreSheet.objects.filter(pk=request.user.id)
    return render(request, 'profile/score_detail.html', {
        'session': session_slug,
        'session_scores': session_scores,
    })



#---------------   State models  --------------------------------
# Competencies
class Language(models.Model):
    """
    A professionaly relevant language competence in both written and spoken
    use.
    """
    LEVEL = (
        (1, 'basic communcation skills'),
        (2, 'good command'),
        (3, 'very good command'),
        (4, 'excellent command'),
        (5, 'near native'),
        (6, 'native speaker')
    )
    profile = models.ForeignKey(Profile, blank=True)
    name = models.CharField(max_length=50, verbose_name="Language")
    prof_written = models.IntegerField(choices=LEVEL,verbose_name="Written command")
    prof_spoken = models.IntegerField(choices=LEVEL, verbose_name="Verbal command")

    def __str__(self):
        return self.name

# Student Courses/Exmpeirnce
class Course(models.Model):
    """A relevant Course taken by a Student to be displayed in their profile"""
    profile = models.ForeignKey(Profile)
    subject = models.CharField(max_length=25, choices=PRACTICE_FIELDS)
    title = models.CharField(max_length=100)
    year = models.CharField(verbose_name="Year you have taken the course", max_length=20)
    instructor = models.CharField(max_length=70, blank=True, null=True)
    institution_abbr = models.CharField(max_length=10, blank=True, null=True)
    institution = models.CharField(max_length=100, blank=True, null=True)

ApplicationManagement/templates/review/review_list.html
{% extends "base_assessment.html" %}


{% block assessment-header %}
<div class="row">
    <div class="col-sm-8">
        <h2>Application Review - Submission</h2>
        {% comment %}REVIEWED APPLICATION LIST{% endcomment %}
        <h3>Reviewed Applications</h3>
        <table class="table table-striped table-hover">
            <thead class="thead-default">
                <tr>
                    <td>Country</td>
                    <td>Applicant</td>
                    <td>Competition Exp</td>
                    <td>Intern.Exp</td>
                    <td>Coursework</td>
                    <td>Overall</td>
                </tr>
            </thead>
            <tbody>
                {% for review in review_list %}
                <tr class="table-success">
                    <td><img src="{{review.application.applicant.user.profile.country.flag}}" alt=""> {{review.application.applicant.user.profile.country.name}}</td>
                    <td><a href="{% url 'application:review_applicationdetail' review.application.applicant.user.username %}">{{review.application.applicant.user.get_full_name}}</a></td>

                    <td></td>
                    <td>{{review.question_1}}</td>
                    <td>{{review.question_2}}</td>
                    <td>{{review.question_3}}</td>
                    <td>{{review.question_4}}</td>
                </tr>
                {% endfor %}        
            </tbody>
        </table>
        <!--  Open Applications -->
        <h3>Unreviewed Applications</h3>
        <table class="table table-striped table-hover">
            <thead class="thead-default">
                <tr>
                    <td>University</td>
                    <td>Members</td>
                </tr>
            </thead>
            <tbody>
                {% for team in review_list_open %}             
                    <tr class="table-warning">
                        <td><a href="{% url 'application:assess_team' team.slug %}">{{team.university}}</a></td>
                        {% for member in team.members.all %}
                        <td>{{member.user.get_full_name}}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}        
            </tbody>
        </table>
            
    </div>
    <div class="col-sm-4">
        <aside class="card">
            <header class="card-header">
                <div class="row">
                    <div class="col-sm-4">
                        <img class="img-fluid" src="{{ member.user.profile.profileImg.url }}" alt="">
                    </div>
                    <div class="col-sm-8">
                        <h5>{{ member.role|capfirst }}</h5>
                        <img src="{{ member.user.profile.country.flag }}" alt=""> {{ member.user.profile.country.name}}
                        <h3>{{ member.user.get_full_name }}</h3>

                    </div>
                </div>
            </header>
            <article class="card-block">
                <header>
                    <h4>Competition Experience</h4>
                </header>
                <table class="table table-sm table-striped table-hover">
                    <thead class="thead-default">
                        <tr>
                            <td>Country</td>
                            <td>Name</td>
                            <td>Year</td>
                            <td>Days</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for competition in member.user.profile.competition_set.all %}
                            <tr>
                                <td><img src="{{ competition.country.flag}}" alt=""> {{ competition.country.name }}</td>
                                <td>{{ competition.name}}</td>
                                <td>{{ competition.year }}</td>
                                <td>{{ competition.duration }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </article>
            {% comment %}{% endcomment %}
            <article class="card-block">
                <header>
                    <h4>International Experience</h4>
                </header>
                <table class="table table-sm table-striped table-hover">
                    <thead>
                        <tr>
                            <td>Country</td>
                            <td>Position</td>
                            <td>Employer</td>
                            <td>Duration</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for internship in member.user.profile.internship_set.all %}
                            <tr>
                                <td><img src="{{ internship.country.flag }}" alt=""> {{ internship.country.name }}</td>
                                <td>{{ internship.position }}</td>
                                <td>{{ internship.employer }}</td>
                                <td>{{ internship.duration}} {{ internship.measure}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </article>
            {% comment %}{% endcomment %}
            <article class="card-block">
                <header>
                    <h4>Relevant Coursework <span>{{member.}}</span></h4>
                </header>
                <table class="table table-sm table-striped table-hover">
                    <thead>
                        <tr>
                            <td>Subject</td>
                            <td>Title</td>
                            <td>Employer</td>
                            <td>Duration</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for course in member.user.profile.studentprofile.course_set.all %}
                            <tr>
                                <td>{{ course.get_subject_display }}</td>
                                <td>{{ course.title }}</td>
                                <td>{{ course.institution_abbr }}</td>
                                <td>{{ course.duration}} {{ course.measure}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </article>
        </aside>
    </div>
</div>
{% endblock assessment-header %}


{% block assessment-presentation %}
Present the individual Team members as Cards here, summary description
{% endblock assessment-presentation %}

{% block scoring-section %}
Scoring Section
{% endblock scoring-section %}

ApplicationManagement/templates/review/teamreview_scoresheet.html
{% extends 'base_assessment.html' %}

{% block assessment-header %}
<h3>Scoring View / Summary Description</h3>
<div class="card-group">
    {% for member in team.applicant.team.members.all %}
        <section class="card">
            <header class="card-header">
                <div class="row">
                    <div class="col-sm-4">
                        <img class="img-fluid" src="{{ member.user.profile.profileImg.url }}" alt="">
                    </div>
                    <div class="col-sm-8">
                        <h5>{{ member.role|capfirst }}</h5>
                        <img src="{{ member.user.profile.country.flag }}" alt=""> {{ member.user.profile.country.name}}
                        <h3>{{ member.user.get_full_name }}</h3>

                    </div>
                </div>
            </header>
            <article class="card-block">
                <header>
                    <h4>Competition Experience</h4>
                </header>
                <table class="table table-sm table-striped table-hover">
                    <thead class="thead-default">
                        <tr>
                            <td>Country</td>
                            <td>Name</td>
                            <td>Year</td>
                            <td>Days</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for competition in member.user.profile.competition_set.all %}
                            <tr>
                                <td><img src="{{ competition.country.flag}}" alt=""> {{ competition.country.name }}</td>
                                <td>{{ competition.name}}</td>
                                <td>{{ competition.year }}</td>
                                <td>{{ competition.duration }}</td>
                            </tr>
                        {% endfor %}
                        <tr class="table-success">
                            <td>Rating: </td>
                            <td><input type="text" style="width: 80px;"></td>
                        </tr>
                    </tbody>
                </table>
            </article>
            {% comment %}{% endcomment %}
            <article class="card-block">
                <header>
                    <h4>International Experience</h4>
                </header>
                <table class="table table-sm table-striped table-hover">
                    <thead>
                        <tr>
                            <td>Country</td>
                            <td>Position</td>
                            <td>Employer</td>
                            <td>Duration</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for internship in member.user.profile.internship_set.all %}
                            <tr>
                                <td><img src="{{ internship.country.flag }}" alt=""> {{ internship.country.name }}</td>
                                <td>{{ internship.position }}</td>
                                <td>{{ internship.employer }}</td>
                                <td>{{ internship.duration}} {{ internship.measure}}</td>
                            </tr>
                        {% endfor %}
                        <tr class="table-success">
                            <td>Rating: </td>
                            <td><input type="text" style="width: 80px;"></td>
                        </tr>
                    </tbody>
                </table>

            </article>
            {% comment %}{% endcomment %}
            <article class="card-block">
                <header>
                    <h4>Relevant Coursework</h4>
                </header>
                <table class="table table-sm table-striped table-hover">
                    <thead>
                        <tr>
                            <td>Subject</td>
                            <td>Title</td>
                            <td>Employer</td>
                            <td>Duration</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for course in member.user.profile.studentprofile.course_set.all %}
                            <tr>
                                <td>{{ course.get_subject_display }}</td>
                                <td>{{ course.title }}</td>
                                <td>{{ course.institution_abbr }}</td>
                                <td>{{ course.duration}} {{ course.measure}}</td>
                            </tr>
                        {% endfor %}
                        <tr class="table-success">
                            <td>Rating: </td>
                            <td><input type="text" style="width: 80px;"></td>
                        </tr>
                    </tbody>
                </table>

            </article>
        </section>
    {% endfor %}
</div>
{% endblock assessment-header %}

{% block assessment-presentation %}
    
    {% for member in team.applicant.team.members.all %}
        <article class="row">
            <header class="col-sm-2">
                <div class="card">
                    <div class="card-header">
                        <img src="{{ member.user.profile.country.flag }}" alt=""> {{ member.user.profile.country.name}}
                        <h3 class="card-title">{{ member.user.get_full_name }}</h3>
                        <img class="img-fluid" src="{{ member.user.profile.profileImg.url }}" alt="">
                        <h5>{{ member.role|capfirst }}</h5>
                    </div>
                    {% comment %}{% endcomment %}
                    <ul class="list-group list-group-flush">
                        {% comment %}<h4>Awards</h4>{% endcomment %}
                        
                        {% for award in member.user.profile.award_set.all %}
                            <li class="list-group-item">
                                {{ award.competition }} /  {{ award.competition.year }}
                                <p><strong>{{ award.title }}</strong></p>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                    
            </header>
            <content class="col-sm-10">
                <h4>Competition Experience</h4>
                <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <td>Country</td>
                                <td>Name</td>
                                <td>Year</td>
                                <td>Days</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for competition in member.user.profile.studentprofile.competition_set.all %}
                                <tr>
                                    <td><img src="{{ competition.country.flag}}" alt=""> {{ competition.country.name }}</td>
                                    <td>{{ competition.name}}</td>
                                    <td>{{ competition.year }}</td>
                                    <td>{{ competition.duration }} {{ competition.measure}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                <h4>International Experience</h4>
                <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <td>Field</td>
                                <td>Country</td>
                                <td>Position</td>
                                <td>Employer</td>
                                <td>Duration</td>
                                <td>Year</td>
                                <td>Scope of Work</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for internship in member.user.profile.studentprofile.internship_set.all %}
                                <tr>
                                    <td>{{ internship.get_field_of_practice_display }}</td>
                                    <td><img src="{{ internship.country.flag }}" alt=""> {{ internship.country.name }}</td>
                                    <td>{{ internship.position }}</td>
                                    <td>{{ internship.employer }}</td>
                                    <td>{{ internship.duration}} {{ internship.measure}}</td>
                                    <td>{{ internship.year}}</td>
                                    <td>{{ internship.descr }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                <h4>Relevant Coursework</h4>
                <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <td>Institution</td>
                                <td>Subject</td>
                                <td>Title</td>
                                <td>Instructor</td>
                                <td>Duration</td>
                                <td>Learnings</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for course in member.user.profile.studentprofile.course_set.all %}
                                <tr>
                                    <td>{{ course.institution_abbr }}</td>
                                    <td>{{ course.get_subject_display }}</td>
                                    <td>{{ course.title }}</td>
                                    <td>{{ course.instructor }}</td>
                                    <td>{{ course.duration}} {{ course.measure}}</td>
                                    <td>{{ course.learnings}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </content>
        </article>
    {% endfor %}
        
{% endblock assessment-presentation %}

{% block scoring-section %}

{% endblock scoring-section %}