Portal/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'portal'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^competition/$', views.CompetitionIndex.as_view(), name='competition'),
    url(r'^venue/$', views.VenueIndex.as_view(), name="venues"),
    url(r'^venue/manage/$', views.VenueManagementView.as_view(), name="manage_venue"),
    url(r'^venue/create/$', views.VenueCreate.as_view(), name='create_venue'),
    url(r'^venue/(?P<slug>.+)/', views.VenueDetailView.as_view(), name="venue_detail"),
    url(r'^teams/$', views.TeamListView.as_view(), name='teams'),
    url(r'^teams/(?P<slug>[\w\-]+)/$', views.TeamDetailView.as_view(), name="team_profile"),
    url(r'^teams/(?P<slug>[\w\-]+)/edit/$', views.TeamEditView.as_view(), name="edit_team"),
    url(r'^experts/$', views.ExpertListView.as_view(), name='experts'),
    url(r'^expert/(?P<slug>[\w\.]+)/$', views.ExpertDetailView.as_view(), name='expert_profile'),
    url(r'^students/$', views.StudentListView.as_view(), name="students"),
    url(r'^student/(?P<slug>[\w\.]+)/', views.StudentDetailView.as_view(), name='student_profile'),
    url(r'^session/', include('SessionManagement.urls')),
]

Portal/models.py
from django.db import models

# Create your models here.

Portal/forms.py
from django import forms
from UserManagement.models import Student, Expert, Staff, Team

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Div, Field

# -- EXPERT Section ------
class ExpertSearchForm(forms.Form):
    name = forms.CharField(max_length=150)
    nationality = forms.CharField(max_length=100)
    languages = forms.CharField(max_length=100)
    affiliation = forms.CharField(max_length=100)

    def __init__(self, *args, **kwargs):
        super(ExpertSearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal form-sm'
        self.helper.add_input(Submit('search expert', 'Search expert', css_class='btn-success'))
        self.helper.label_class = 'col-sm-3'
        self.helper.field_class = 'col-sm-9'

# ---- TEAM Section ------
class TeamSearchForm(forms.Form):
    name = forms.CharField(max_length=100)
    country = forms.CharField(max_length=100)
    role = forms.CharField(max_length=100)

class TeamEditForm(forms.ModelForm):
    class Meta:
        model = Team
        exclude = ['role', 'administrativeComment', 'blacklisted', 'slug', 'user']

Portal/views.py
from django.shortcuts import render
from UserManagement.models import (Student, Expert, Team, TeamProfile, 
                                    StudentProfile, ExpertProfile)
from UserManagement.models import (MediationExperience, NegotiationExperience, 
                                    Course)
from SessionManagement.models import (Venue, Room, Session)
from django.contrib.auth.models import User

# Utils import
from django.db.models import Q, F
# CBGV Imports
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
# CBGV Mixins
from django.views.generic.edit import FormMixin

# FORMS:::
from .forms import ExpertSearchForm, TeamSearchForm, TeamEditForm
# from .forms import TeamEditForm
from SessionManagement.forms import (VenueCreateForm)

# Create your views here.
class IndexView(ListView):
    model = Student
    template_name = 'portal/index.html'

    def get_context_data(self):
        context = super(IndexView, self).get_context_data()
        context['experts_invited'] = Expert.objects.all()
        context['teams_invited'] = Team.objects.all()
        context['venues'] = Venue.objects.all()
 
        return context

class CompetitionIndex(ListView):
    template_name = 'portal/competition/competition_index.html'
    model = Session

    def get_context_data(self):
        context = super(CompetitionIndex, self).get_context_data()
        context['sessionList_current'] = Session.objects.all()
        context['sessionList_upcoming'] = Session.objects.all()
        context['todays_venues'] = Venue.objects.all()
        context['todays_teams'] = Team.objects.all()
        return context


#  -------- VENUE Section --------------
class VenueIndex(ListView):
    model = Venue
    template_name = 'portal/venues/venue_index.html'

class VenueManagementView(ListView):
    model = Venue
    template_name = 'portal/venues/venue_list.html'

class VenueCreate(CreateView):
    model = Venue
    form_class = VenueCreateForm
    template_name = 'session/forms/venueCreate_form.html'

class VenueDetailView(DetailView):
    model = Venue
    template_name = 'portal/venues/venue_detailview.html'
    context_object_name = 'location'

    def get_context_data(self, object):
        context = super(VenueDetailView, self).get_context_data()
        context['geolocation'] = object.geolocation
        return context

# ---- TEAMS Section ---------
class TeamListView(FormMixin, ListView):
    model = Team
    form_class = TeamSearchForm
    template_name = 'portal/teams/team_listview.html'

class TeamDetailView(DetailView):
    model = Team
    template_name = 'portal/teams/team_detailview.html'

class TeamEditView(UpdateView):
    model = Team
    template_name = 'portal/teams/team_editview.html'
    form_class = TeamEditForm

# --- EXPERTS Section --------
class ExpertListView(ListView):
    model = Expert
    context_object_name = 'expert_list'
    template_name = 'portal/experts/expert_list.html'

    def get_context_data(self):
        context = super(ExpertListView, self).get_context_data()
        context['medExp_list'] = MediationExperience.ROLES
        context['negExp_list'] = NegotiationExperience.ROLES
        context['search_form'] = ExpertSearchForm()
        return context

class ExpertDetailView(DetailView):
    model = ExpertProfile
    context_object_name = 'expert'
    template_name = 'portal/experts/expert_detail.html'
    slug_field = 'user__username'


#  ---- STUDENT Section ----------
class StudentListView(ListView):
    model = StudentProfile
    template_name = 'portal/students/student_list.html'
    context_object_name = 'student_list'


class StudentDetailView(DetailView):
    model = StudentProfile
    slug_field = 'user__username'
    template_name = 'portal/students/student_detail.html'
    context_object_name = 'student'

    def get_context_data(self, object):
        context = super(StudentDetailView, self).get_context_data()
        context['negotiationCourses'] = Course.objects.filter(subject='negotiation')
        context['mediationCourses'] = Course.objects.filter(subject='mediation')
        return context

Portal/templates/portal/index.html
{% extends 'base.html' %}
{% load static %}

{% block css-includes %}
<link rel="stylesheet" href="{% static 'main_portal.css' %}">
{% endblock %}

{% block content %}
<section class="competition teaser_section row">
    <section class="container">
        <header>
            <h2>The Competition</h2>
        </header>
    </section>
</section>
<section class="venue teaser_section row">
    <section class="container">
        <header class="row">
            <h2>The Venues</h2>
            {% for venue in venues %}
            <a href="{% url 'portal:venue_detail' venue.slug %}">
            <article class="venue_teaser col-sm-3">
                <header>
                    <img class="img-responsive" src="{% if venue.img_venue %}{{ venue.img_venue.url }}{% else %} https://placehold.it/240x160 {% endif %}" alt="" class="img-responsive">
                </header>
            </article>
            </a>
            {% endfor %}
        </header>
    </section>
</section>
<section class="teams teaser_section row">
    <section class="container">
        <header>
            <h2>The Teams</h2>
            {% for team in teams_invited %}
            <a href="{% url 'portal:team_profile' team.slug %}">
            <article class="row team-teaser">
                <header>
                    <div class="col-sm-3 team-label">
                        <small><img src="{{ team.country.flag }}" alt=""> {{ team.country.name}}</small>
                        <h3>{{ team.university }}</h3>
                        <p>{{ team.slogan }}</p>
                        <ul class="team-members list">
                            {% for member in team.studentprofile_set.all %}
                            <li>{{ member.user.get_full_name }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-sm-9 team-img">
                        <img  class="img-responsive" src="{% if team.teamImg %}{{ team.teamImg.url}}{% else %}https://placehold.it/640x220{% endif %}" alt="">
                    </div>

                    <h4></h4>
                </header>
            </article>
            </a>
            {% endfor %}
        </header>
    </section>
</section>
<section class="row teaser_section experts">
    <section class="container">
        <div class="row">
            <header>
                <h2>The Experts</h2>
            </header>
            {% for expert in experts_invited %}
            <a href="{% url 'portal:expert_profile' expert.user.username %}">
                <article class="col-xs-6  col-sm-4 col-md-3">
                    <header>
                        <img src="{% if expert.user.profile.profileImg %}{{ expert.user.profile.profileImg.url }} {% else %}https://placehold.it/190x180 {% endif %}" alt="">
                        <h4>{{ expert.user.get_full_name }}</h4>
                    </header>
                    <content class="expert_overlay">
                        {{ expert.user.profile.position }}</br>
                        {{ expert.expertprofile.affiliation }}
                    </content>
                </article>
                </a>
            {% endfor %}
        </div>
        
    </section>
</section>

{% endblock content %}