Portal/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'portal'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^competition/$', views.CompetitionIndex.as_view(), name='competition'),
    url(r'^venue/$', views.VenueIndex.as_view(), name="venues"),
    url(r'^venue/manage/$', views.VenueManagementView.as_view(), name="manage_venue"),
    url(r'^venue/create/$', views.VenueCreate.as_view(), name='create_venue'),
    url(r'^venue/(?P<slug>.+)/', views.VenueDetailView.as_view(), name="venue_detail"),
    url(r'^teams/$', views.TeamListView.as_view(), name='teams'),
    url(r'^teams/(?P<slug>[\w\-]+)/$', views.TeamDetailView.as_view(), name="team_profile"),
    url(r'^teams/(?P<slug>[\w\-]+)/edit/$', views.TeamEditView.as_view(), name="edit_team"),
    url(r'^experts/$', views.ExpertListView.as_view(), name='experts'),
    url(r'^expert/(?P<slug>[\w\.]+)/$', views.ExpertDetailView.as_view(), name='expert_profile'),
    url(r'^students/$', views.StudentListView.as_view(), name="students"),
    url(r'^student/(?P<slug>[\w\.]+)/', views.StudentDetailView.as_view(), name='student_profile'),
    url(r'^session/', include('SessionManagement.urls')),
]

UserManagement/urls.py
from django.conf.urls import url
from . import views as profile_views

app_name = 'userManagement'

urlpatterns = [
    url(r'^$', profile_views.ProfileDisplayView.as_view(), name='profile'),
    url(r'create/$', profile_views.profile_create, name='profile_create'),
    url(r'^edit/$', profile_views.profile_edit, name='profile_edit'),
    url(r'^delete/$', profile_views.profile_delete, name='profile_delete'),
    url(r'^test/$', profile_views.TestView.as_view(), name="test"),
]
# Profile Registration ulrs
urlpatterns += [
]
# Scoring Related Views
urlpatterns += [
    # url(r'^scores/$', profile_views.score_list, name='scores'),
    # url(r'^scores/(?P<session_slug>.+)/$', profile_views.score_detail, name='sessionScores'),

]

Portal/models.py
from django.db import models

# Create your models here.

UserManagement/models.py
from datetime import datetime
from django.conf import settings
# General Imports

from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
# Automatic Account Association between User and Attendent Account in Registration
from django.db.models.signals import post_save
from django.dispatch import receiver
# Country Field import
from django_countries.fields import CountryField
# URL resolvers
from django.urls import reverse
# Calculation imports
from django.db.models import (Avg, StdDev, Sum, Max, Min)


PRACTICE_FIELDS = (
        ('negotiation', 'Negotiation'),
        ('mediation', 'Mediation'),
        ('arbitration', 'Arbitratiion')
    )
# -------------------  Roles within the Competition  ------------------

class Attendent(models.Model):
    """A Person attending the Competiton. Information stored to keep track
    on Applications before and behaviour during Competition over Time.
    Reused in later application processes."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=35, choices= settings.STUDENT_ROLES + settings.EXPERT_ROLES + settings.STAFF_ROLES)
    blacklisted = models.BooleanField(default=False)
    administrativeComment = models.TextField(blank=True, null=True)


    # Store Information on the Current Year for easy retrieval
    current_application = None

    def get_current_application(self):
        """
        Used to get the current application from inside a template.
        Returns None when no application present.
        """
        application = self.application_set.get(competition_year='2017')
        if application:
            return application
        else:
            return None

    def get_ratings(self, year=datetime.now().year):
        # Catch all given Feedback
        if self.feedback_set.all():
            # Calculate the AVG Values
            return self.feedback_set.filter(expert=self.user.attendent, date__year=year).aggregate(Avg('feedbackQuality'), Avg('feedbackRelated'), Avg('feedbackComm'))
        else:
            return None

    def get_absolute_url(self):
        return reverse('portal:expert_profile', args = [self.user.username])

    def __str__(self):
        return "{}".format(self.user.get_full_name())
    
    def save(self, *args, **kwargs):
        self.current_application = self.application_set.filter(competition_year=settings.START_DATE.year)
        super(Attendent, self).save(*args, **kwargs)


# This automatically creates an Attendent Instance for every User on save
# @receiver(post_save, sender=User)
# def create_attendent_profile(sender, instance, created, **kwargs):
#     if created:
#         Attendent.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_attendent_profile(sender, instance, **kwargs):
#     instance.attendent.save()



class Expert(Attendent):
    """
    
    """
    # Expert related Feedback Scores
    pass

class Team(Attendent):
    """Group of Students applying from a University for the Competition.
    Consisting of individual Team Members and an Associated Coach."""
    university = models.CharField(max_length=100)
    university_logo = models.ImageField(upload_to='team/university_logo/', blank=True)
    country = CountryField(null=True)
    teamImg = models.ImageField(upload_to='team/teampictures/', blank=True)
    slug = models.SlugField(blank=True, null=True)
    members = models.ManyToManyField(Attendent, related_name="teammembers")

    def __str__(self):
        return self.university
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.university)
        self.role = 'team'
        super().save(*args, **kwargs)


class Student(Attendent):
    """
    Can be in role(Mediator, Negotiator). profile 
    """
    # This needs to be initialized when the student is 
    university = models.OneToOneField(Team, null=True, blank=True)

class Staff(Attendent):
    """
    Will be used to manage and represent all necessary information on a Staff Member for Shift Management.
    """
    pass


# ---Basic Profile Models to store additional Information on the Applicants
class Profile(models.Model):
    """
    """
    attendent = models.OneToOneField(Attendent, blank=True, null=True, on_delete=models.CASCADE)
    bio = models.TextField(max_length=2000)
    slogan = models.CharField(max_length=250, verbose_name="Your favorite quote up to 250 characters")
    country = CountryField(null=True)
    city = models.CharField(max_length=50, verbose_name='City of Residence')
    profileImg = models.ImageField(upload_to='profileImg/%Y/%m/%d', blank=True, null=True)

    # Contact Details
    phoneNumber = models.CharField(verbose_name="Your Phone Number", max_length=100, blank=True, null=True)

    # Social Media Accounts
    twitter = models.URLField(verbose_name="Twitter Account",
    blank=True, null=True)
    linkedin = models.URLField(verbose_name="LinkedIn Account",
    blank=True, null=True)
    facebook = models.URLField(verbose_name="Facebook Account",
    blank=True, null=True)
    blog = models.URLField(verbose_name="Website",
    blank=True, null=True)

    def __str__(self):
        return str(self.attendent)

class ExpertProfile(Profile):
    """
    """
    coachedTeam = models.ForeignKey(Team, related_name="coachedTeam", null=True, blank=True)  
    affiliation = models.CharField(max_length=100)
    position = models.CharField(max_length=100)

    # Special Certifications and Memberships
    imi_certified = models.BooleanField(verbose_name="Are you IMI Certified?", default=False)
    viac_member = models.BooleanField(verbose_name="Are you Member of VIAC?", default=False)
    iba_member = models.BooleanField(verbose_name="Are you Member of IBA?", default=False)

class StudentProfile(Profile):
    """
    Stores all relevant information on the Student as either(Negotiator, Mediator) in the
    competition. Is used for professional representation, sharing of information.
    It does NOT store relevant Scoringinformation etc.(= stored on ATTENDENT )
    """
    # student = models.OneToOneField(Student, null=True, on_delete=models.CASCADE)
    
    # relevant practical Experience
    def get_absolute_url(self):
        return reverse('portal:student_profile', args=[self.attendent.user.username])

class TeamProfile(models.Model):
    """ Stores all relevant Information about the Team as the object of a Application.
    Relevant information about the Applicants as part of the team are stored in the
    'Student Profile' and assTociated to the Team Instance."""
    team = models.OneToOneField(Team, null=True, blank=True)
    languages_spoken = models.CharField(max_length=100, blank=True)

    # Application Relevant Information
    presentation_text = models.TextField(max_length=4000, blank=True)
    application_letter = models.FileField(verbose_name="Upload your motivation letter",
    upload_to='applications/teams/motivationletter/', 
    blank=True, null=True)

    application_video = models.FileField(verbose_name="Upload Application Video",
    blank=True, null=True) 

    # Additional Profile Information
    def __str__(self):
        return self.team.university
        
@receiver(post_save, sender=Team)
def create_tem_profile(sender, instance, created, **kwargs):
    if created:
        TeamProfile.objects.create(team=instance)

@receiver(post_save, sender=Team)
def save_team_profile(sender, instance, **kwargs):
    instance.teamprofile.save()


class StaffProfile(Profile):
    """
    Stores all relevant information on the Student as either(Negotiator, Mediator) in the
    competition. Is used for professional representation, sharing of information.
    It does NOT store relevant Scoringinformation etc.(= stored on ATTENDENT )
    """ 
    staff = models.OneToOneField(Staff, null=True, on_delete=models.CASCADE)
    
    # relevant practical Experience
    def get_absolute_url(self):
        return reverse('portal:student_profile', args=[self.attendent.user.username])


#----------------- Interaction models -------------------------

# ----- Feedback / Scoring Views --------
def score_list(request):
    score_list = ScoreSheet.objects.filter(pk=request.user.id)
    return render(request, 'profile/score_list.html', {
        'score_list': score_list,
    })

def score_detail(request, session_slug):
    session_scores = ScoreSheet.objects.filter(pk=request.user.id)
    return render(request, 'profile/score_detail.html', {
        'session': session_slug,
        'session_scores': session_scores,
    })



#---------------   State models  --------------------------------
# Competencies
class Language(models.Model):
    """
    A professionaly relevant language competence in both written and spoken
    use.
    """
    LEVEL = (
        (1, 'basic communcation skills'),
        (2, 'good command'),
        (3, 'very good command'),
        (4, 'excellent command'),
        (5, 'near native'),
        (6, 'native speaker')
    )
    profile = models.ForeignKey(Profile, blank=True)
    name = models.CharField(max_length=50, verbose_name="Language")
    prof_written = models.IntegerField(choices=LEVEL,verbose_name="Written command")
    prof_spoken = models.IntegerField(choices=LEVEL, verbose_name="Verbal command")

    def __str__(self):
        return self.name

# Student Courses/Exmpeirnce
class Course(models.Model):
    """A relevant Course taken by a Student to be displayed in their profile"""
    profile = models.ForeignKey(Profile)
    subject = models.CharField(max_length=25, choices=PRACTICE_FIELDS)
    title = models.CharField(max_length=100)
    year = models.CharField(verbose_name="Year you have taken the course", max_length=20)
    instructor = models.CharField(max_length=70, blank=True, null=True)
    institution_abbr = models.CharField(max_length=10, blank=True, null=True)
    institution = models.CharField(max_length=100, blank=True, null=True)

Portal/forms.py
from django import forms
from UserManagement.models import Student, Expert, Staff, Team

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Div, Field

# -- EXPERT Section ------
class ExpertSearchForm(forms.Form):
    name = forms.CharField(max_length=150)
    nationality = forms.CharField(max_length=100)
    languages = forms.CharField(max_length=100)
    affiliation = forms.CharField(max_length=100)

    def __init__(self, *args, **kwargs):
        super(ExpertSearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal form-sm'
        self.helper.add_input(Submit('search expert', 'Search expert', css_class='btn-success'))
        self.helper.label_class = 'col-sm-3'
        self.helper.field_class = 'col-sm-9'

# ---- TEAM Section ------
class TeamSearchForm(forms.Form):
    name = forms.CharField(max_length=100)
    country = forms.CharField(max_length=100)
    role = forms.CharField(max_length=100)

class TeamEditForm(forms.ModelForm):
    class Meta:
        model = Team
        exclude = ['role', 'administrativeComment', 'blacklisted', 'slug', 'user']

Portal/views.py
from django.shortcuts import render
from UserManagement.models import (Student, Expert, Team, TeamProfile, 
                                    StudentProfile, ExpertProfile)
from UserManagement.models import (MediationExperience, NegotiationExperience, 
                                    Course)
from SessionManagement.models import (Venue, Room, Session)
from django.contrib.auth.models import User

# Utils import
from django.db.models import Q, F
# CBGV Imports
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
# CBGV Mixins
from django.views.generic.edit import FormMixin

# FORMS:::
from .forms import ExpertSearchForm, TeamSearchForm, TeamEditForm
# from .forms import TeamEditForm
from SessionManagement.forms import (VenueCreateForm)

# Create your views here.
class IndexView(ListView):
    model = Student
    template_name = 'portal/index.html'

    def get_context_data(self):
        context = super(IndexView, self).get_context_data()
        context['experts_invited'] = Expert.objects.all()
        context['teams_invited'] = Team.objects.all()
        context['venues'] = Venue.objects.all()
 
        return context

class CompetitionIndex(ListView):
    template_name = 'portal/competition/competition_index.html'
    model = Session

    def get_context_data(self):
        context = super(CompetitionIndex, self).get_context_data()
        context['sessionList_current'] = Session.objects.all()
        context['sessionList_upcoming'] = Session.objects.all()
        context['todays_venues'] = Venue.objects.all()
        context['todays_teams'] = Team.objects.all()
        return context


#  -------- VENUE Section --------------
class VenueIndex(ListView):
    model = Venue
    template_name = 'portal/venues/venue_index.html'

class VenueManagementView(ListView):
    model = Venue
    template_name = 'portal/venues/venue_list.html'

class VenueCreate(CreateView):
    model = Venue
    form_class = VenueCreateForm
    template_name = 'session/forms/venueCreate_form.html'

class VenueDetailView(DetailView):
    model = Venue
    template_name = 'portal/venues/venue_detailview.html'
    context_object_name = 'location'

    def get_context_data(self, object):
        context = super(VenueDetailView, self).get_context_data()
        context['geolocation'] = object.geolocation
        return context

# ---- TEAMS Section ---------
class TeamListView(FormMixin, ListView):
    model = Team
    form_class = TeamSearchForm
    template_name = 'portal/teams/team_listview.html'

class TeamDetailView(DetailView):
    model = Team
    template_name = 'portal/teams/team_detailview.html'

class TeamEditView(UpdateView):
    model = Team
    template_name = 'portal/teams/team_editview.html'
    form_class = TeamEditForm

# --- EXPERTS Section --------
class ExpertListView(ListView):
    model = Expert
    context_object_name = 'expert_list'
    template_name = 'portal/experts/expert_list.html'

    def get_context_data(self):
        context = super(ExpertListView, self).get_context_data()
        context['medExp_list'] = MediationExperience.ROLES
        context['negExp_list'] = NegotiationExperience.ROLES
        context['search_form'] = ExpertSearchForm()
        return context

class ExpertDetailView(DetailView):
    model = ExpertProfile
    context_object_name = 'expert'
    template_name = 'portal/experts/expert_detail.html'
    slug_field = 'user__username'


#  ---- STUDENT Section ----------
class StudentListView(ListView):
    model = StudentProfile
    template_name = 'portal/students/student_list.html'
    context_object_name = 'student_list'


class StudentDetailView(DetailView):
    model = StudentProfile
    slug_field = 'user__username'
    template_name = 'portal/students/student_detail.html'
    context_object_name = 'student'

    def get_context_data(self, object):
        context = super(StudentDetailView, self).get_context_data()
        context['negotiationCourses'] = Course.objects.filter(subject='negotiation')
        context['mediationCourses'] = Course.objects.filter(subject='mediation')
        return context

Portal/templates/portal/experts/expert_detail.html
{% extends 'base_profile.html' %}

{% block profile-header %}

<div class="container">
    <article class="row">
        <header class="col-sm-4">
            <div class="card">
                <!--Profile Picture-->
                <div class="card-header">
                    <div class="row">
                        <div class="col-sm-5">
                            <img class="img-fluid" src="{% if attendent.profile.profileImg %}{{ attendent.profile.profileImg.url}} {% else %} https://placehold.it/180x180 {% endif %}" alt="">
                        </div>
                        <div class="col-sm-7">
                             <small>{{ attendent.user.attendent.role|capfirst}}</small>
                            <img src="{{ attendent.country.flag}}" alt=""> {{ attendent.country.name}}
                            <h4>{{ attendent.user.get_full_name }}</h4>
                            <div class="float-sm-left">
                                <ul class="list-inline">
                                    <li class='list-inline-item'><a href="{{ attendent.profile.linkedin}}" class="fa fa-linkedin"></a></li>
                                    <li class='list-inline-item'><a href="{{ attendent.profile.twitter}}" class="fa fa-twitter"></a></li>
                                    <li class='list-inline-item'><a href="{{ attendent.profile.facebook}}" class="fa fa-facebook"></a></li>
                                    <li class='list-inline-item'><a href="{{ attendent.profile.instagram}}" class="fa fa-instagram"></a></li>
                                    <li class='list-inline-item'><a href="{{ attendent.profile.google}}" class="fa fa-google"></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div class="card-block">
                    <!--Contact Details-->
                    <table class="table table-sm">
                        <tbody>
                            <tr><td>Phone: </td><td>{{ attendent.profile.phoneNumber}}</td></tr>
                            <tr><td>Email: </td><td>{{ attendent.user.email}}</td></tr>
                            <tr><td>City: </td><td>{{ attendent.profile.city }}</td></tr>
                        </tbody>
                    </table>
                </div>
                <hr>
                <div class="card-footer">
                    <div class="navbar">
                        
                    </div>
                </div>
                {% if request.user.attendent == attendent %}
                    <a href="{% url 'userManagement:profile_edit' %}" role="button" class="btn-block btn-danger">Edit Profile</a>
                {% endif %}
            </div>
        </header>
        <!--Header Detail Section-->
        <content class="col-sm-8">
            <div class="backlink">
            </div>
            <article>
                <header>
                </header>
                <content>
                    <h3>Slogan</h3>
                    <blockquote cite="">
                        {{ attendent.profile.slogan }}
                    </blockquote>
                </content>
            </article>
            <article>
                <header>
                    <h3>Biography</h3>
                </header>
                <content>
                    <p>{{ attendent.profile.bio }}</p>
                </content>
            </article>
        </content>
    </section>
</div>
{% endblock %}

<!--          MAIN BODY            -->

{% comment %}   SIDEBAR   {% endcomment %}
{% block profile-content %}

<!--        DISPLAY ONLY FOR attendent THEMSELVES                          -->

{% if request.user.profile.attendentprofile == attendent %}
    <!--Personal Information Feedback-->
    <section class="row">
        <article class="col-sm-6">
            <article class="row">
                <header>
                    <h4>Upcoming Appointments</h4>
                </header>
                <content>Scheduled Appointments can be displayed here.</content>
            </article>

            <article class="row">
                <header>
                    <h4>Messages</h4>
                </header>
                <content>
                    <!--This is one message-->
                    <article class="row">
                        <header class="col-sm-3">
                            <small>Sent 12:45, 2/3/2017</small>
                            <h5>Marc Aurelius</h5>
                            <p></p>
                        </header>
                        <content class="col-sm-9">
                            <p>Hey this is the message text that i sent you.</p>
                        </content>
                    </article>
                    <article class="row">
                        <header class="col-sm-3">
                            <small>Sent 12:45, 2/3/2017</small>
                            <h5>Marc Aurelius</h5>
                            <p></p>
                        </header>
                        <content class="col-sm-9">
                            <p>Hey this is the message text that i sent you.</p>
                        </content>
                    </article>


                </content>
            </article>
        </article>
        <article class="col-sm-6">
            <article class="row">
                <header>
                    <h4>Score Results</h4>
                </header>
                <content>Display the scores that have been put in so far here.</content>
            </article>

            <article class="row">
                <header>
                    <h4>Score Results</h4>
                </header>
                <content>Display the scores that have been put in so far here.</content>
            </article>

        </article>
    </section>
{% endif %}

<!--        DISPLAY ONLY FOR attendent THEMSELVES                          -->
<section class="row">
        <h3>Upcoming Programs/Trainings</h3>
        {% for program in attendent.program_set.all %}
            <a href="{{program.webpage.url}}">
            <article class="col-sm-6">
                
                <header class="col-sm-12">
                    <p>{{ program.year }}</p>
                    <small></small>
                    <h4>{{ program.title }}</h4>
                </header>
                <aside class="col-sm-4">
                    <h5>{{ program.institution}}</h5>
                    <ul class="list-unstyled">
                        <li>Instructor: {{ program.attendent.user.get_full_name }}</li>
                        <li>Duration: {{ program.duration }} Hours</li>
                    </ul>
                </aside>
                <content class="col-sm-8">
                    <h5>Program Content</h5>
                    <p>{{ program.description }}</p>
                </content>
            </article></a>
            {% endfor %}
            {% for course in mediationCourses %}
                <article class="row">
                
                <header class="col-sm-12">
                    <p>{{ course.year }}</p>
                    <small></small>
                    <h4>{{ course.title }}</h4>
                </header>
                <aside class="col-sm-4">
                    <h5>{{ course.institution}}</h5>
                    <ul class="list-unstyled">
                        <li>Instructor: {{ course.instructor }}</li>
                        <li>Duration: {{ course.duration }} Hours</li>
                    </ul>
                </aside>
                <content class="col-sm-8">
                    <h5>Course Content</h5>
                    <p>{{ course.learnings }}</p>
                </content>
            </article>
            {% endfor %}
        </section>
    

<section class="row">
    <aside class="col-sm-4">
        <h3>Certifications</h3>
        
        {% for certificate in attendent.certification_set.all %}
            <article class="row">
                <header class="col-sm-12">
                    <h4>{{certificate.title}}</h4>
                    
                </header>
                <content class="col-sm-12">
                    <small>{{ certificate.issueDate }} ( {{ certificate.institution }} )</small>
                </content>
            </article>
        {% endfor %}
            

        <article class="row">
            <h3>Languages</h3>
            
            {% for language in attendent.language_set.all %}
                <header>
                    <h4>{{ language.name }}</h4>
                </header>
                <table>
                    <tbody>
                        <tr><td>Spoken: </td><td>{{ language.get_prof_spoken_display|capfirst }}</td></tr>
                        <tr><td>Written: </td><td>{{ language.get_prof_written_display|capfirst }}</td></tr>
                    </tbody>
                </table>
            {% endfor %}
                
        </article>
    </aside>

{% comment %}   MAIN CONTENT   {% endcomment %}
    <main class="col-sm-8">
        <!-- Awards -->
        <section class="row">
            <h3>Mediation Experience</h3>
            {% for experience in attendent.mediationexperience_set.all %}
            <article class="row">
                <div class="col-sm-12">
                    <h5>{{ experience.get_profession_display|capfirst }}</h5>
                    <ul class="list-inline">
                        <li>{{ experience.duration }} Years of Experience</li>
                        <li><img src="{{ experience.country.flag }}" alt=""> {{ experience.country.name }}</li>
                        <li>{{ experience.cases }} Cases worked</li>
                    </ul>
                </div>
                <header class="col-sm-6">
                    <h4>Clients worked with</h4>
                    <p>{{ experience.priorClients }}</p>
                    <small></small>
                </header>
                <content class="col-sm-6">
                    <small></small>
                    <h4>Places worked from</h4>
                    <p>{{ experience.placesWorked }}</p>
                </content>
            </article>
        {% endfor %}
        </section>


        <section class="row">
            <h3>Negotiation Experience</h3>
            {% for experience in attendent.negotiationexperience_set.all %}
            <article class="row">
                <div class="col-sm-12">
                    <h5>{{ experience.get_profession_display|capfirst }}</h5>
                    <ul class="list-inline">
                        <li>{{ experience.duration }} Years of Experience</li>
                        <li><img src="{{ experience.country.flag }}" alt=""> {{ experience.country.name }}</li>
                        <li>{{ experience.cases }} Cases worked</li>
                    </ul>
                </div>
                <header class="col-sm-6">
                    <h4>Clients worked with</h4>
                    <p>{{ experience.priorClients }}</p>
                    <small></small>
                </header>
                <content class="col-sm-6">
                    <small></small>
                    <h4>Places worked from</h4>
                    <p>{{ experience.placesWorked }}</p>
                </content>
            </article>
        {% endfor %}
        </section>


        <!--Relevant Coursework -->
    </main>

</section>
{% endblock %}

Portal/templates/portal/experts/expert_list.html
{% extends 'base_profile.html' %}
{% load crispy_forms_tags %}

{% block profile-header %}
<section class="jumbotron">
    <div class="container">
        <header>
            <h2>CDRC Expert Selection</h2>
        </header>
        <content class="row">
            <div class="searchBox col-sm-4">
                <h4>by Mediation Experience</h4>
                <form action="" method="GET">
                    {% for role in medExp_list %}
                        <div class="">
                            <label for="id_{{role}}">{{ role.1 }}</label>
                            <input type="checkbox" name="id_{{role.1}}" value="{{ role.1 }}" class="">
                        </div>
                    {% endfor %}
                </form>
            </div>
            <div class="searchBox col-sm-4">
                <h4>by Negotiation Experience</h4>
                <form action="" method="GET">
                    {% for role in negExp_list %}
                        <div class="">
                            <label for="id_{{role.1}}">{{role.1}}</label>
                            <input type="checkbox" name="id_{{role.1}}" value="{{role.1}}" class="">
                        </div>
                    {% endfor %}
                </form>
            </div>
            <div class="searchBox col-sm-4">
                <h4>Find an Expert</h4>
                {% csrf_token %}
                {% crispy search_form %}
            </div>
        </content>
    </div>
</section>
{% endblock %}

{% block profile-content %}
    {% for expert in expert_list %}
    <a href="{% url 'portal:expert_profile' expert.user.username %}">
        <article class="list_item row">
            <header class="col-sm-3">
                <img src="{% if expert.user.profile.profileImg %}{{ expert.user.profile.profileImg.url }}{% else %}https://placehold.it/180x190{% endif %}" alt="">
                <small class="row"><img src="{{ expert.user.profile.country.flag}}" alt=""> {{ expert.user.profile.country.name}} </small>
            </header>
            <content class="col-sm-9">
                <h3>{{ expert.user.get_full_name }}</h3>
                <h4>{{expert.user.profile.expertprofile.position|capfirst}}, {{ expert.user.profile.expertprofile.affiliation|capfirst }} </h4>
                <p>{{ expert.user.profile.bio|truncatewords:100 }}</p>
            </content>
            
        </article>
    </a>
    {% endfor %}
{% endblock %}