Dashboard/urls.py
from django.conf.urls import url

# View Imports
from . import views

app_name = "dashboard"

urlpatterns = [
    url(r'^$', views.DashboardIndex.as_view(), name='index'),
    # Set of Dashboard Views to control the other modules
    url(r'^settings/$', views.DashboardSettings.as_view(), name='index_settings'),
    url(r'^settings/expert_application/$', views.DashboardExpert.as_view(), name='index_expert'),
    url(r'^settings/team_application/$', views.DashboardTeam.as_view(), name='index_team'),
    url(r'^settings/venue_management/$', views.DashboardVenue.as_view(), name='index_venue'),
    url(r'^settings/session_management/$', views.DashboardSession.as_view(), name='index_session'),
    url(r'^settings/shift_management/$', views.DashboardShift.as_view(), name='index_shift'),
    # The Dashboard Module Views
    url(r'^experts/$', views.expert_management, name='manage_experts'),
    url(r'^experts/(?P<username>.+)/$', views.expert_management, name="expert_detail"),
    url(r'^sessions/$', views.SessionManagement.as_view(), name="manage_sessions"),
    url(r'^teams/$', views.applicationoverview_team, name='manage_teams'),
    url(r'^teams/(?P<slug>[-\w]+)/$', views.team_management, name='team_detail'),
    url(r'^venues/$', views.VenueManagement.as_view(), name='manage_venues'),
    url(r'^venues/(?P<slug>[-\w]+)/$', views.VenueManagement.as_view(), name='manage_venue_detail'),
    url(r'^shifts/$', views.ShiftManagement.as_view(), name='manage_shifts'),
    # Accept and Decline Applications directly
    url(r'^accept/(?P<pk>\d+)/$', views.accept_application, name='accept_application'),
    url(r'^decline/(?P<pk>\d+)/$', views.decline_application, name='decline_application'),
    url(r'^test/$', views.test_model, name='test'),
]

Portal/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'portal'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^competition/$', views.CompetitionIndex.as_view(), name='competition'),
    url(r'^venue/$', views.VenueIndex.as_view(), name="venues"),
    url(r'^venue/manage/$', views.VenueManagementView.as_view(), name="manage_venue"),
    url(r'^venue/create/$', views.VenueCreate.as_view(), name='create_venue'),
    url(r'^venue/(?P<slug>.+)/', views.VenueDetailView.as_view(), name="venue_detail"),
    url(r'^teams/$', views.TeamListView.as_view(), name='teams'),
    url(r'^teams/(?P<slug>[\w\-]+)/$', views.TeamDetailView.as_view(), name="team_profile"),
    url(r'^teams/(?P<slug>[\w\-]+)/edit/$', views.TeamEditView.as_view(), name="edit_team"),
    url(r'^experts/$', views.ExpertListView.as_view(), name='experts'),
    url(r'^expert/(?P<slug>[\w\.]+)/$', views.ExpertDetailView.as_view(), name='expert_profile'),
    url(r'^students/$', views.StudentListView.as_view(), name="students"),
    url(r'^student/(?P<slug>[\w\.]+)/', views.StudentDetailView.as_view(), name='student_profile'),
    url(r'^session/', include('SessionManagement.urls')),
]

SessionManagement/urls.py
from django.conf.urls import url
from . import views 


app_name = "session"

urlpatterns = [
    url(r'^$', views.SessionListView.as_view(), name='overview'),
    url(r'^create/$', views.SessionCreateView.as_view(), name='session_create'),
    url(r'^(?P<slug>[\w\-]+)/$', views.SessionDetailView.as_view(), name="session_detail"),
    url(r'^(?P<slug>[\w\-]+)/edit/$', views.SessionEditView.as_view(), name="session_edit"),
]

Dashboard/models.py
from django.db import models

# Create your models here.

SessionManagement/models.py
import requests
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
from UserManagement.models import Student, Expert, Team, Staff, ExpertProfile, TeamProfile, StudentProfile, StaffProfile
# Import for Google Maps Plugin
from django_google_maps import fields as map_fields
from django.utils.text import slugify

from datetime import timedelta, date, datetime
# --------------Location Management -------------------


# Define general helper Functions
START_DATE = datetime(2017, 8, 5)
END_DATE = datetime(2017, 8, 12)
def daterange(start_date, end_date):
        """
        Returns a generator object to be used for the construction of 
        planning tables to manage Time Availabilities.
        """
        for n in range(int((end_date - start_date).days)):
            yield start_date + timedelta(n)

def geocode(lat, lng):
    base = "http://maps.googleapis.com/maps/api/geocode/json?"
    params = "latlng={lat},{lon}&sensor=false".format(
        lat=lat,
        lon=lng
    )
    url = "{base}{params}".format(base=base, params=params)
    response = requests.get(url)
    return response.json()['results'][0]['formatted_address']


class Venue(models.Model):
    """A specific location that houses rooms where Sessions take place."""
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, null=True)
    img_venue = models.ImageField(upload_to="venues/locationImg/", blank=True)
    # Google Maps Plugin - LocationInformation
    map_img = models.FileField(upload_to='venues/locationMap/', blank=True)
    address = map_fields.AddressField(max_length=200, null=True)
    geolocation = map_fields.GeoLocationField(max_length=100, null=True)
    
    directions = models.TextField(max_length=350, null=True)
    location_info = models.TextField(max_length=1000, null=True)

    # Management Relevant Information
    BOOKING_STATUS = (
        (1, 'inquired'),
        (2, 'reserved'),
        (3, 'confirmed')
    )

    booking_status = models.IntegerField(choices = BOOKING_STATUS)

    def get_status(self):
        return self.booking_status

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse_lazy('portal:venue_detail', args=[self.slug])
            

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.address = geocode(self.geolocation.lat, self.geolocation.lon)
        super().save(*args, **kwargs)
        

    
    
class Room(models.Model):
    """A specific Room available to be assigned to a session."""
    venue = models.ForeignKey(Venue)
    name = models.CharField(max_length=60)
    slots = {}

    # Comment section for information as to equipment and specials
    directions = models.TextField(max_length=2000, null=True)
    level = models.CharField(max_length=50, null=True)
    notes = models.TextField(blank=True, null=True)    
    # Display information
    img_presentation = models.ImageField(upload_to="venues/presentationImg/", blank=True)
    
    # Management related hidden fields
    _internal_comments = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name 

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    
    def check_timeslots(self):
        days = {key:None for key in daterange(START_DATE, END_DATE)}
        availabilities = self.availability_set.all()
        for day in days:
            for slot in availabilities:
                if slot.free_from.day == day.day:
                    days[day] = slot
        return days

# -----  STATE MODELS ----------
class Availability(models.Model):
    """
    A continous stretch of available time for a given Room
    to be used with a Session.
    """
    room = models.ForeignKey(Room)
    slug = models.SlugField(blank=True)
    free_from = models.DateTimeField()
    free_till = models.DateTimeField()

    # Calculate amount of time available in this stretch
    def schedule(self, session):
        """
        Checks if the Time associated with the Session planned fits
        within the given availability. Returns Boolean answer.
        """
        return True

    def get_duration(self):
        duration = self.free_from - self.free_till
        return duration 
    
    def check_available(self, Session):
        if Session.startTime > self.free_from and Session.endTime <= self.free_till:
            return True
        else:
            return False

    def __str__(self):
        return self.room.name
    # TODO: Turn the location ino GPS for displaying on a map

    def save(self, *args, **kwargs):
        self.slug = slugify(self.room.name)
        super().save(*args, **kwargs)

# ---------------Session Management-----------------------
class Session(models.Model):
    """A specific Round of Mediation between two Negotiating Teams and a Mediator
    scheduled for a given Date and Time in a room at a certain Venue."""
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)
    # The Teams taking part
    mediatorTeam = models.ForeignKey(Team, related_name="mediatorteam")
    negotiatorTeam = models.ForeignKey(Team, related_name="negotiatorteam")

    # The Assessors taking part
    assessors = models.ManyToManyField(ExpertProfile)

    # The Room scheduled
    venue = models.ForeignKey(Venue)
    room = models.ForeignKey(Room)
    # The Timeslot scheduled
    startTime = models.DateTimeField(blank=True, null=True)
    endTime = models.DateTimeField(blank=True, null=True)
    # Additional Ressources Scheduled
    notes = models.TextField(blank=True, null=True)


    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('session:session_detail', args=[self.slug])

# ----------------Work Management-------------------------
class Shift(models.Model):
    """A flexible amount of time a given Person is available for Work at the Comp."""
    staff = models.ForeignKey(Staff)
    start = models.DateTimeField()
    end = models.DateTimeField()

    def __str__(self):
        return "{} to {}".format(self.start, self.end)

Dashboard/forms.py
from django import forms
from UserManagement.models import Team, Student, Expert, Staff

# Model Imports
from ApplicationManagement.models import Application

# Crispy Addons
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Field, Button, ButtonHolder, Submit

# EXPERT MANAGEMENT ---------------
class ExpertCommentForm(forms.Form):
    comment = forms.CharField(
        label="Comments on Application", 
        max_length=250, 
        widget=forms.Textarea,
        required=False,
        )
    blacklisted = forms.BooleanField(required=False)
    status = forms.ChoiceField(
        label="Application Status",
        choices = Application.SELECTION_STATUS
    )

    def __init__(self, *args, **kwargs):
        super(ExpertCommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Save', css_class="btn-success"), )


class TeamCommentForm(forms.Form):
    comment = forms.CharField(
        label="Comments on Application", 
        max_length=250, 
        widget=forms.Textarea,
        required=False,
        )
    
    status = forms.ChoiceField(
        label="Application Status",
        choices = Application.SELECTION_STATUS
    )

    def __init__(self, *args, **kwargs):
        super(TeamCommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Save', css_class="btn-success"), )
        

SessionManagement/forms.py
from django import forms
from .models import (Venue, Room)
from .models import (Session, Availability, Shift)

# Define the Forms here. 
class SessionModelForm(forms.ModelForm):
    class Meta:
        model = Session
        exclude = []

class SessionCreateForm(forms.ModelForm):
    class Meta:
        model = Session
        exclude = []

class SessionEditForm(forms.ModelForm):
    class Meta:
        model = Session
        exclude = []


class VenueCreateForm(forms.ModelForm):
    class Meta:
        model = Venue
        exclude = []

SessionManagement/views.py
from django.shortcuts import render, HttpResponsePermanentRedirect
from django.urls import reverse
from .forms import (SessionModelForm, SessionCreateForm, SessionEditForm)
from .models import Session
# CBGV Imports
from django.views.generic.edit import (CreateView, DeleteView, UpdateView)
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

# Create your views here.
class SessionCreateView(CreateView):
    model = Session
    form_class = SessionCreateForm
    template_name = 'session/forms/sessionCreate_form.html'
    # success_url = reverse('session:session_list')

class SessionDetailView(DetailView):
    model = Session
    template_name = 'session/session_detail.html'

class SessionListView(ListView):
    model = Session
    template_name = 'session/session_list.html'

class SessionEditView(UpdateView):
    model = Session
    template_name = 'session/forms/sessionEdit_form.html'
    form_class = SessionEditForm
    success_url = ('/sessions/')

Dashboard/templates/dashboard/dashboard_index.html
{% extends "base_dashboard_index.html" %}


{% block overview-head %}
<div class="container">
    <div class="row">
    <header class="col-sm-12">
        <h2>Dashboard</h2>
    </header>
    
    <section class="col-sm-8">
        Control Settings and overview
    </section>
</div>
</div>
{% endblock overview-head %}

{% block content-main %}
<h2>Main Content</h2>
<section class="row">
    <header>
        <h3>Sessions</h3>
    </header>
    <content>
        Display a paginated list of all sessions ordered by day and automatically 
        subset to upcoming only
    </content>`
</section>

<section class="row">
    <header>
        <h3>Teams</h3>
    </header>
    <content>
        Currently engaged Teams, Scores and current ranking of Teams here
    </content>
</section>

<section class="row">
    <header>
        <h3>Experts</h3>
    </header>
</section>

<section class="row">
    <header>
        <h3>Rooms</h3>
    </header>
    <content>
        Information on the rooms booked by session, current information on the people
        repsonsible and the status of the room readiness for the next session.
    </content>
</section>
<section class="row">
    <header>
        <h3>Venues</h3>
    </header>
</section>
{% endblock content-main %}

{% block content-sidemenue %}
<h2>Sidemenue</h2>
<article class="row">
    <header>
        <h3>Shift</h3>
    </header>
    <content>
        The current shifts, and associated information 
        to notes, contact details, responsibilities etc..
    </content>
</article>

<article class="row">
    <header>
        <h3>Shift</h3>
    </header>
</article>
{% endblock content-sidemenue %}

Dashboard/templates/dashboard/session_management.html
{% extends "base_dashboard.html" %}

{% block overview-head %}
<h2>Session Management</h2>
<article>
    <header  class="col-sm-8">
        <h3>Sessions by Days</h3>
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <td>Date</td>
                    <td>Round</td>
                    <td>Med.Team</td>
                    <td>Neg.Team</td>
                    <td>Assessor A</td>
                    <td>Assessor B</td>
                    <td>Assessor C</td>
                    <td></td>                    
                </tr>
            </thead>
            <tbody>
                
                {% for session in session_list %}
                <tr>
                    <td>{{session.startTime|date:'d.M'}}</td>
                    <td>{{session.name}}</td>
                    <td>{{session.mediatorTeam}}</td>
                    <td>{{session.negotiatorTeam}}</td>
                    
                    
                        
                    <td>{{session.}}</td>
                </tr>
                {% endfor %}
                    
            </tbody>
        </table>
    </header>
    <content class="col-sm-4">
        <h3>Edit Session Details</h3>
        <article class="row">
            <header>
                <h5>Assessors</h5>
            </header>
            <content>
                {% for assessor in selected_session.assessors.all %}
                    <small>{{assessor.user.get_full_name}}</small>
                {% endfor %} 
            </content>
        </article>
        {% comment %}{% endcomment %}
        <article class="row">
            <header>
                <h5>Shift</h5>
            </header>
            <content>

            </content>
        </article>
        {% comment %}{% endcomment %}
        <article>
            <header>
                <h5>Comments</h5>
            </header>
            <content>

            </content>
        </article>
    </content>
</article>
{% endblock overview-head %}

{% block content-main %}
<h3>Competition Planning and Results</h3>
{% endblock content-main %}

{% block content-sidemenue %}
{% endblock content-sidemenue %}

Dashboard/templates/dashboard/shift_management.html
{% extends "base_dashboard.html" %}

{% block overview-head %}
{% endblock overview-head %}

{% block content-main %}
{% endblock content-main %}

{% block content-sidemenue %}
{% endblock content-sidemenue %}

Dashboard/templates/dashboard/teamreview_index.html
{% extends 'base_dashboard.html' %}

{% block subnavigation %}
Subnavigation for T
{% endblock subnavigation %}

{% block overview-head %}
<div class="row">
    <div class="col-sm-4">
       <div class="card">
           <div class="card-header">
                <h2>Team Applications</h2>
           </div>

           <ul class="list-group list-group-flush">
                <li class="list-group-item"><a class="card-link" href="{% url 'dashboard:manage_teams' %}">Overall Ranking </a></li>
                <li class="list-group-item"><a class="card-link" href="{% url 'dashboard:manage_teams' %}">Finished Reviews 4/34</a></li>
                <li class="list-group-item"><a class="card-link" href="{% url 'dashboard:manage_teams' %}">Unfinished Reviews 30/34</a></li>
            </ul>

       </div>
    </div>
    <div class="col-sm-8">
        <h3>Overall Ranking</h3>
        <table class="table table-striped table-hover">
            <thead class="thead-default">
                <tr>
                    <td>No.</td>
                    <td>Continent</td>
                    <td>University</td>
                    <td>Country</td>
                    <td>Team</td>
                    <td>Video</td>
                    <td class="table-success">Total</td>
                    <td>Application Status</td>
                    <td></td>
                </tr>
            
            </thead>
            <tbody>
                {% for application in team_applications %}
                    <tr>
                        <td class="text-center table-warning">{{ application.overall_rank }}</td>
                        <td class="text-center">{{ application.continent_rank }}</td>
                        <td><a href="{% url 'dashboard:team_detail' application.applicant.team.slug %}">{{ application.applicant.team.university }}</a></td>
                        <td><img src="{{ application.applicant.team.country.flag }}" alt=""> {{ application.applicant.team.country.name }}</td>
                        <td>{{ application.memberreview_score|floatformat:"2" }}</td>
                        <td>{{ application.videoreview_score|floatformat:"2" }}</td>
                        <td class="table-success">{{ application.application_score|floatformat:"2" }}</td>
                        <td>{{ application.get_review_status_display }}</td>
                        <td  {% if application.selection_status == 3%}class="table-success" {% elif application.selection_status == 2 %} class="table-danger"{% endif %}><div class="btn-group">
                            <a href="{% url 'dashboard:accept_application' application.id %}?next={{ request.path }}" name="" id="" class="btn btn-success btn-sm "><i class="fa fa-check" aria-hidden="true"></i></a>
                            <a href="{% url 'dashboard:decline_application' application.id %}?next={{ request.path }}" name="" id="" class="btn btn-danger btn-sm "><i class="fa fa-close" aria-hidden="true"></i></a>
                        </div>
                        </td>
                    </tr>
            	{% endfor %}
            </tbody>
        </table>
    </div>
</article>

{% endblock overview-head %}

{% block content-header %}
<h3>Ranking Statistics</h3>

<!--Display the Inidividual RANKINGS FOR EACH CONTINENT -->
<section class="row">
    {% for continent, continent_list in teamlists.items %}
        <div class="col-sm-6">
            <h3>{{ continent }}</h3>
            <table class="table table-striped table-hover">
                <thead class="thead">
                    <tr>
                        <td>Local</td>
                        <td>Global</td>
                        <td>University</td>
                        <td>Country</td>
                        <td>Total</td>
                        <td>Video</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    {% for application in continent_list %}
                    <tr>
                        <td class="text-center table-warning">{{ application.continent_rank }}</td>
                        <td>{{ application.overall_rank }} / {{ team_applications|length }}</td>
                        <td {% if application.selection_status == 3 %} class="table-success" {% elif application.selection_status == 2 %} class="table-danger" {% endif %} ><a href="{% url 'dashboard:team_detail' application.applicant.team.slug %}">{{ application.applicant.team.university }}</a></td>
                        <td><img src="{{application.applicant.team.country.flag}}" alt=""> {{ application.applicant.team.country.name }}</td>
                        <td>{{ application.application_score|floatformat:"2" }}</td>
                        <td>{{ application.videoreview_score|floatformat:"2"}}</td>
                        {% comment %}{% for member in application.applicant.team.members.all %}
                        <td>{{ member.score }}</td>
                        {% endfor %}{% endcomment %}
                        <td><div class="btn-group">
                            <a href="{% url 'dashboard:accept_application' application.id %}?next={{ request.path }}" name="" id="" class="btn btn-success btn-sm "><i class="fa fa-check" aria-hidden="true"></i></a>
                            <a href="{% url 'dashboard:decline_application' application.id %}?next={{ request.path }}" name="" id="" class="btn btn-danger btn-sm "><i class="fa fa-close" aria-hidden="true"></i></a>
                        </div>
                            
                    </tr> 
                    {% endfor %} 
                </tbody>
            </table>
        </div>
    {% endfor %}            
</section>
{% endblock content-header %}


{% block content-sidemenue %}
{% endblock content-sidemenue %}

{% comment %}{% endcomment %}
{% block content-main %}


{% endblock content-main %}

{% comment %}Subblock {% endcomment %}
{% block scoring-section %}
<section class="row">
    <h3>Summary Statistics</h3>
</section>
{% endblock scoring-section %}

Dashboard/templates/dashboard/test.html
{% extends "base_dashboard.html" %}

{% block overview-head %}
<h3>Team Application</h3>
<table class="table table-hover">
    <tr>
        <td>{{team}}</td>
    </tr>
    <tr>
        <td>q1_score</td>
        <td>q2_score</td>
        <td>q3_score</td>
        <td>q4_score</td>
    </tr>
    <tr>
        <td>{{team.q1_score}}</td>
        <td>{{team.q2_score}}</td>
        <td>{{team.q3_score}}</td>
        <td>{{team.q4_score}}</td>
    </tr>
    <tr>
        <td>Team Average Score</td>
        <td>{{team.team_avg_scores}}</td>
    </tr>
    <tr>
        <td>member Average Score</td>
        <td>{{team.member_avg_scores}}</td>
    </tr>
</table>

<h3>Expert Application</h3>
<table class="table table-hover">
    <tr>
        <td>{{expert}}</td>
    </tr>
    <tr>
        <td>q1_score</td>
        <td>q2_score</td>
        <td>q3_score</td>
        <td>q4_score</td>
    </tr>
    <tr>
        <td>{{expert.q1_score}}</td>
        <td>{{expert.q2_score}}</td>
        <td>{{expert.q3_score}}</td>
        <td>{{expert.q4_score}}</td>
    </tr>
</table>
{% endblock overview-head %}

Dashboard/templates/dashboard/venue_management.html
{% extends "base_dashboard.html" %}

{% block overview-head %}
<article class="row">
        <header class="col-sm-8">
            <h3>Venue Overview</h3>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <td>Status</td>
                        <td>Venue</td>
                        <td>Rooms</td>
                        <td>Sessions</td>
                    </tr>
                </thead>
                <tbody>
                {% for venue in venue_list %}
                    <tr>
                        <td>{{venue.get_booking_status_display}}</td>
                        <td><a href="{% url 'dashboard:manage_venue_detail' venue.slug %}">{{venue.name}}</a></td>
                        <td>{{venue.room_set.count}}</td>
                        <td>{{venue.session_set.count}}</td>
                        <td>{{venue.location_info|truncatewords:'20'}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </header>
        <content class="col-sm-4">
            <small>Details for </small>
            <h3>{{selected_venue.name}}</h3>
            <small>Sessions scheduled</small>
            <table class="table table-sm">
                <thead>
                    <tr>
                        <td>Date</td>
                        <td>Start</td>
                        <td>End</td>
                        <td>Session</td>
                        <td>Room</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                     
                     {% for session in session_sel %}
                         <tr>
                            <td>{{session.startTime|date:'d.m'}}</td>
                            <td>{{session.startTime|date:'f'}}</td>
                            <td>{{session.endTime|date:'f'}}</td>
                            <td>{{session.name}}</td>
                            <td>{{session.room}}</td>
                            <td>{{session.mediator}}</td>
                        </tr>
                     {% endfor %}
                         
                </tbody>
            </table>
        </content>
    </article>
    
    
{% endblock overview-head %}


{% block content-sidemenue %}
<article class="col-sm-4">
<h3>Shift Management</h3>
<table>
    <thead>

    </thead>
    <tbody>
        <tr>
            <td>Info about the people working shifts at this building</td>
        </tr> 
    </tbody>
</table>
</article>
{% endblock content-sidemenue %}



{% block content-main %}
    {% comment %}Room Management{% endcomment %}
        <article class="">
            <header>
                <h3>Rooms @ {{selected_venue.name}}</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <td>Room</td>
                            {% for day in competition_days %}
                            <td>{{day|date:'d.m'}}</td>   
                            {% endfor %}                             
                        </tr>
                    </thead>
                    <tbody>
                        {% for room  in rooms_sel %}
                        <tr>
                            <td>{{room.name}}</td>
                            
                            {% for day,slot in room.check_timeslots.items %}
                                <td {% if slot %}class="success"{%else%}class='danger'{%endif%}>
                                    <small>{{slot.free_from|date:'H:i'}} - {{slot.free_till|date:'H:i'}}</small></td>
                            {% endfor %}
                                
                        </tr>
                        {% endfor %}
                            
                    </tbody>
                </table>
            </header>
        </article>
        {% comment %}{% endcomment %}
        
{% endblock content-main %}